# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lisa Charlotte Rost
tagline:          "A world view"
description:      'Thoughts about world models, data visualization and productivity.'
url:              http://lisacharlotterost.github.io
baseurl:          /

author:
  name:           "Lisa Charlotte Rost"
  url:            https://twitter.com/lisacrost

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
